#!/usr/bin/env python3
"""
Reads CSV(s) generated by GenerateObjectURLs_NoDownload_AllChildRecords.py or CombinedDigitalObjectScript.py and downloads
the listed digital objects.

CSV format expected: Parent NAID, Title, Digital Object URL (header row optional)

Usage examples:
  python DownloadObjects_FromCSV.py --csv ObjectsList_123456789_1.csv
  python DownloadObjects_FromCSV.py --dir /path/to/csvs --workers 4 --batch-size 50

This script does NOT call the NARA Catalog API; it only reads the CSV and downloads URLs.
"""

import argparse
import csv
import logging
import os
import queue
import random
import threading
import time
from datetime import datetime
from hashlib import sha1
from urllib.parse import urlparse, unquote

import requests

CHUNK_SIZE = 8192


def safe_name_from_url(url):
    parsed = urlparse(url)
    name = os.path.basename(parsed.path)
    name = unquote(name)
    if not name:
        # fallback to sha1 of url
        name = sha1(url.encode('utf-8')).hexdigest()
    return name


def download_worker(tasks_q, session, args, stats, lock):
    while True:
        try:
            task = tasks_q.get(block=False)
        except queue.Empty:
            return

        parent, title, url = task
        dest_dir = os.path.join(args.output_dir, str(parent))
        os.makedirs(dest_dir, exist_ok=True)
        filename = safe_name_from_url(url)
        out_path = os.path.join(dest_dir, filename)
        temp_path = out_path + '.part'

        if os.path.exists(out_path) and os.path.getsize(out_path) > 0:
            logging.info(f"Skipping existing: {out_path}")
            with lock:
                stats['skipped'] += 1
            tasks_q.task_done()
            # small sleep to avoid too-tight loop
            time.sleep(random.uniform(0, args.jitter))
            continue

        attempt = 0
        while attempt <= args.max_retries:
            attempt += 1
            try:
                start = time.time()
                with session.get(url, stream=True, timeout=args.timeout) as resp:
                    status = resp.status_code
                    if status == 200:
                        total = 0
                        with open(temp_path, 'wb') as fh:
                            for chunk in resp.iter_content(CHUNK_SIZE):
                                if chunk:
                                    fh.write(chunk)
                                    total += len(chunk)

                        os.replace(temp_path, out_path)
                        elapsed = time.time() - start
                        with lock:
                            stats['downloaded'] += 1
                            stats['bytes'] += total
                        logging.info(f"Downloaded: {out_path} ({total} bytes, {elapsed:.1f}s)")
                        break
                    elif status in (429, 503) or 500 <= status < 600:
                        # server busy or error; fall through to backoff
                        logging.warning(f"Server returned {status} for {url}; attempt {attempt}")
                        raise requests.HTTPError(f"Status {status}")
                    else:
                        logging.error(f"Failed to download {url}: HTTP {status}")
                        with lock:
                            stats['failed'] += 1
                        break
            except Exception as e:
                wait = args.base_backoff * (2 ** (attempt - 1)) + random.uniform(0, args.jitter)
                logging.warning(f"Error downloading {url}: {e} — backing off {wait:.1f}s (attempt {attempt})")
                time.sleep(wait)
                if attempt > args.max_retries:
                    logging.error(f"Giving up on {url} after {attempt-1} attempts")
                    with lock:
                        stats['failed'] += 1

        # per-request randomized short sleep so bursts are smoothed
        time.sleep(args.base_delay + random.uniform(0, args.jitter))

        # batch-level sleep
        with lock:
            stats['completed_since_batch'] += 1
            if stats['completed_since_batch'] >= args.batch_size:
                logging.info(f"Completed {stats['completed_since_batch']} downloads; batch sleep {args.batch_sleep}s")
                time.sleep(args.batch_sleep)
                stats['completed_since_batch'] = 0

        tasks_q.task_done()


def parse_csv_paths(csv_path=None, csv_dir=None):
    paths = []
    if csv_path:
        if os.path.isdir(csv_path):
            for fname in os.listdir(csv_path):
                if fname.lower().endswith('.csv'):
                    paths.append(os.path.join(csv_path, fname))
        elif os.path.isfile(csv_path):
            paths.append(csv_path)
    if csv_dir:
        for fname in os.listdir(csv_dir):
            if fname.lower().endswith('.csv'):
                paths.append(os.path.join(csv_dir, fname))
    return sorted(set(paths))


def read_tasks_from_csv(csv_paths):
    tasks = []
    for p in csv_paths:
        with open(p, 'r', encoding='utf-8', errors='replace') as fh:
            reader = csv.reader(fh)
            headers = None
            for row in reader:
                if not row:
                    continue
                # try to detect header row
                if headers is None and any('url' in c.lower() or 'object' in c.lower() for c in row):
                    headers = row
                    continue

                # Support rows with 1, 2 or 3+ columns
                if len(row) == 1:
                    parent = 'unknown'
                    title = ''
                    url = row[0].strip()
                elif len(row) == 2:
                    parent = row[0].strip()
                    title = ''
                    url = row[1].strip()
                else:
                    parent = row[0].strip()
                    title = row[1].strip()
                    url = row[2].strip()

                if url:
                    tasks.append((parent or 'unknown', title, url))
    return tasks


def human_readable_bytes(n):
    for unit in ['B', 'KB', 'MB', 'GB', 'TB']:
        if n < 1024.0:
            return f"{n:.1f}{unit}"
        n /= 1024.0
    return f"{n:.1f}PB"


def main():
    parser = argparse.ArgumentParser(description='Download files listed in CSV(s) with rate-limiting and backoff')
    parser.add_argument('--csv', help='Path to CSV file or directory containing CSVs (default: ObjectsList_*.csv in CWD)')
    parser.add_argument('--dir', dest='csv_dir', help='Directory containing CSVs')
    parser.add_argument('--output-dir', default='downloads', help='Directory to write downloaded files (default: downloads)')
    parser.add_argument('--workers', type=int, default=4, help='Number of concurrent download workers (default: 4)')
    parser.add_argument('--base-delay', type=float, default=0.5, help='Base per-request delay in seconds (default: 0.5)')
    parser.add_argument('--jitter', type=float, default=0.5, help='Max randomized jitter in seconds added to sleeps (default: 0.5)')
    parser.add_argument('--batch-size', type=int, default=50, help='Number of downloads per batch before a longer sleep (default: 50)')
    parser.add_argument('--batch-sleep', type=float, default=10.0, help='Seconds to sleep after each batch (default: 10s)')
    parser.add_argument('--max-retries', type=int, default=4, help='Max retries per file on failure (default: 4)')
    parser.add_argument('--base-backoff', type=float, default=1.0, help='Base backoff seconds for exponential retry (default: 1s)')
    parser.add_argument('--timeout', type=float, default=30.0, help='HTTP request timeout in seconds (default: 30s)')
    parser.add_argument('--log', default=None, help='CSV path to write download log (default: downloads/download_log.csv)')
    args = parser.parse_args()

    # find CSVs
    csv_paths = parse_csv_paths(args.csv, args.csv_dir)
    if not csv_paths:
        # default: any ObjectsList_*.csv in cwd
        csv_paths = [os.path.abspath(f) for f in os.listdir('.') if f.startswith('ObjectsList_') and f.lower().endswith('.csv')]

    if not csv_paths:
        print('No CSV files found. Provide --csv or --dir, or put ObjectsList_*.csv in current directory.')
        return

    tasks = read_tasks_from_csv(csv_paths)
    if not tasks:
        print('No download tasks found in CSV files.')
        return

    os.makedirs(args.output_dir, exist_ok=True)
    log_path = args.log or os.path.join(args.output_dir, 'download_log.csv')

    logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s: %(message)s')

    tasks_q = queue.Queue()
    for t in tasks:
        tasks_q.put(t)

    stats = {
        'downloaded': 0,
        'failed': 0,
        'skipped': 0,
        'bytes': 0,
        'completed_since_batch': 0,
    }
    lock = threading.Lock()

    session = requests.Session()
    adapter = requests.adapters.HTTPAdapter(max_retries=0)
    session.mount('http://', adapter)
    session.mount('https://', adapter)

    workers = []
    for i in range(args.workers):
        t = threading.Thread(target=download_worker, args=(tasks_q, session, args, stats, lock), daemon=True)
        t.start()
        workers.append(t)

    start_time = time.time()
    # Wait for queue to be processed
    try:
        while any(t.is_alive() for t in workers):
            time.sleep(0.5)
    except KeyboardInterrupt:
        logging.warning('Interrupted by user; exiting...')

    elapsed = time.time() - start_time

    # write summary log
    with open(log_path, 'w', encoding='utf-8', newline='') as lf:
        writer = csv.writer(lf)
        writer.writerow(['timestamp', 'downloaded', 'failed', 'skipped', 'bytes', 'elapsed_seconds'])
        writer.writerow([datetime.utcnow().isoformat() + 'Z', stats['downloaded'], stats['failed'], stats['skipped'], stats['bytes'], f"{elapsed:.1f}"])

    print('\nDownload summary:')
    print(f"  Files downloaded: {stats['downloaded']}")
    print(f"  Files skipped: {stats['skipped']}")
    print(f"  Files failed: {stats['failed']}")
    print(f"  Bytes downloaded: {human_readable_bytes(stats['bytes'])}")
    print(f"  Elapsed time: {elapsed:.1f}s")
    if elapsed > 0 and stats['bytes'] > 0:
        print(f"  Average speed: {human_readable_bytes(stats['bytes']/elapsed)}/s")


if __name__ == '__main__':
    main()
